// Generated by CoffeeScript 1.8.0
(function() {
  var data, pos;

  pos = {
    x: 100,
    y: 200,
    dump: function() {
      return "x:" + this.x + ", y:" + this.y;
    }
  };

  data = new pos();

  console.log(data.dump());

}).call(this);
