// Generated by CoffeeScript 1.8.0
(function() {
  window.onload = function() {
    var elm;
    elm = document.createElement("input");
    elm.type = "button";
    elm.value = "ボタン";
    elm.onclick = function() {
      alert("hoge");
      return document.body.appendChild(elm);
    };
    return document.body.appendChild(elm);
  };

}).call(this);
